### ISSUE TITLE
Remove redundant rollup config

### ISSUE THREAD

**Issue by gvidon** [ottofeller/hooks#1]
This was once added in order to deal with formik. I think it is now safe to remove:
https://github.com/ottofeller/hooks/blob/fcaf2d16955db05217ce32b56dfc7dce9bdda096/rollup.config.js#L22-L27

**Comment by gvidon** [comment]
@Serator please clean the redundant code on this week. @pufflik is busy with kutir.

**Comment by Serator** [comment]
https://github.com/ottofeller/hooks/commit/00a0cad327394b500821c066d697c8c7694f15c3
